### ISSUE TITLE
App down -> Ex Libris issue

### ISSUE THREAD

**Issue by Raphael-Rey** [HSG-Library/alma-copy-user-roles#15]
Dear Jonas,

It seems that this App like SLSP Card encounter actually an issue with Ex Libris.

It doesn't work anymore.

I opened an Ex Libris case with high priority about this issue. I mentionned Copy User Roles to explain that the issue is not of the app itself.

Do you have useful information about the issue, I could transmit to Ex Libris?

Best regards,

Raphaël

**Comment by d22** [comment]
Hi @Raphael-Rey 
Thanks for opening an issue at ExLibris, I also posted to the developer forum: https://developers.exlibrisgroup.com/?post_type=topic&p=73338 (post is currently pending).

It seems to be an issue with Content Security Policies:
<img src="https://snipboard.io/eJwivO.jpg">

I think we have to see what ExLibris has to say.
br
Jonas

**Comment by d22** [comment]
Hi @Raphael-Rey 
The Apps seem to work again. Did you get any reply by ExLibris? My Forum post is still pending for moderation.
Br 
Jonas

**Comment by Raphael-Rey** [comment]
Hello @d22 ,

We have no precise information. It seems however to be working.

We got only a very short message from the API team to our developer. No explanation on the ticket.

Best regards,

Raphaël

**Comment by d22** [comment]
Let's hope this was a one-time issue. Since we don't know what happened, and everything works fine again, I will close this issue.
