### ISSUE TITLE
allow copy only on specific roles / role area (e.g. fulfillment)

### ISSUE THREAD

**Issue by kathrin77** [HSG-Library/alma-copy-user-roles#21]
Hi Jonas,
I use this app a lot for our staff who take on new responsibilities, to copy the roles from another staff member. However, often only a certain role area needs to be copied. or Would it be possible to allow only certain roles to be copied, e.g. only fulfillment-related roles? It would be great to pick only certain roles to be copied, rather than "all-or-nothing". Also, the app seems to update all roles (even existing ones), at least with a new status date. Is that intended / cannot be avoided? 
Best regards, Kathrin

**Comment by d22** [comment]
Hi @kathrin77 

Thank you for bringing up this issue. After reviewing the API response, it appears that obtaining information about the role area, as displayed in the Alma UI, is not currently supported. The API response for a single role provides the following details:
```json
{
  "status": {
    "value": "ACTIVE",
    "desc": "Active"
  },
  "scope": {
    "value": "HSG",
    "desc": "HSG"
  },
  "role_type": {
    "value": "215",
    "desc": "Fulfillment Services Manager"
  },
  "parameter": []
}
``` 
Unfortunately, there is no specific information about the role area.

Regarding the update of all roles, the API operates in a 'Swap All' mode, where existing fields are replaced with incoming information. This includes roles, and the documentation notes:

> [...]
> The update is done in a 'Swap All' mode: existing fields' information will be replaced with the incoming information. Incoming lists will replace existing lists.
> 
> Exception for this are the following fields:
> 
> roles - if the incoming list does not contain roles, existing roles will be kept.
> [...]

To add new roles, I must retrieve the existing list of roles, append the new roles, and then save the entire list. This process, unfortunately, triggers an update for all roles and results in a new status date.

I will ask in the developer forum, if there is a more efficient way to update user roles.

Best regards,
Jonas

**Comment by kathrin77** [comment]
hi @d22 thanks for the info. "swap all" makes sense, and the status date is not very important. But it would still be nice to copy only certain roles, based on the role type description. Like a checkbox input type where I can select "all" (default) or just a few specific roles to be appended. 
happy new year,
BR Kathrin

**Comment by d22** [comment]
Hello @kathrin77 
The inquiry in the Developer Forum has yielded positive results. @ori229 from ExLibris has responded:

> We’ll add the role’s area in an upcoming Alma version.

If it's not urgent, I will wait until the February release to implement the role selection and see if the change has already been made.

Here is the link to the question in the forum: https://developers.exlibrisgroup.com/forums/topic/user-role-manipulation-via-api/

Kind regards
Jonas

**Comment by kathrin77** [comment]
@d22 it is not urgent! 👍 Let's wait for role area inclusion in API.

**Comment by d22** [comment]
Hi @kathrin77 
A few days ago, in the [developer forum](https://developers.exlibrisgroup.com/forums/topic/user-role-manipulation-via-api/#post-149937), Ori provided a possible solution for the role area issue, using the current API. This way it was possible to implement this feature without waiting for an API adaption, so I just released a new beta version (v1.3.0-beta). It should already be deployed and ready to test.

Can you please have a look at this and tell me if this works as intended?

Thank you and best regards
Jonas

**Comment by d22** [comment]
Hello @kathrin77 

Have you had a chance to review the changes yet?

Thank you and regards,
Jonas

**Comment by kathrin77** [comment]
Hi @d22 sorry for the delay. I tried testing it in production with a real-live example and had the impression that it didn't work (or maybe it was a usability error on my side), but unfortunately was not documenting before/after correctly and was in a hurry :-(. I wanted to give it another try in our premium sandbox but haven't got round to it. I was planning to do it this week though as due to Sandbox reset this weekend, it would be the ideal time to mess around with staff accounts ;-).

**Comment by kathrin77** [comment]
hi @d22 I just tested in our Sandbox. I believe it works as intended, however, there are some usability issues that I found confusing. I will send you some screenshots by e-mail. br, Kathrin
