### ISSUE TITLE
Build issues

### ISSUE THREAD

**Issue by jweisman** [HSG-Library/alma-copy-user-roles#4]
Hi there. Great app! 

We're getting compile issues when trying to publish the app. Looks like _main.component.html_ references `loadUsers`, but that member doesn't exist on the `MainComponent` class. You can see the errors by running `eca build` from the command line in your project directory.

Can you check that and publish a new version? Alternatively, we can submit a pull request with the change. 

Thanks!

**Comment by d22** [comment]
Hi @jweisman 

Thanks for looking into this! I resolved the build issue and created a new release [v1.0.1](https://github.com/HSG-Library/alma-copy-user-roles/releases/tag/v1.0.1). 

Best regards
Jonas

**Comment by jweisman** [comment]
Great- thanks @d22 . The app was successfully published and is available in Alma.
