### ISSUE TITLE
Incomplete roles generate error messages

### ISSUE THREAD

**Issue by Raphael-Rey** [HSG-Library/alma-copy-user-roles#9]
Dear Jonas,

If the role of the user is incomplete in Alma, your app refuse to write the role in the target account.

A partial copy and a list of failed roles might be nice.

Note: I am only reporting the problem, I have not experienced it myself. It's not really easy to create these incomplete roles in Alma.

Best regards,

Raphaël

![error_message](https://user-images.githubusercontent.com/99899683/170208275-ddfdebb6-33e1-46ed-b8f9-ed3d0c1f35bb.jpg)

**Comment by d22** [comment]
Hi  @Raphael-Rey 

I'am well aware of this issue, but sadly, at the moment, there is no easy solution for this. But I'll try to review my implementation and improve the error reporting.

In case anyone is interested, I can provide background information about this issue.

Greetings
Jonas

**Comment by Raphael-Rey** [comment]
Dear Jonas,

I have a ticket to Ex Libris on this general problem. It occurs with Alma API, too. If you have some documentation, I could explain that it occurs with cloud apps too.

Best regards,

Raphaël

**Comment by mschwendener** [comment]
Hi
Yes, just skipping the roles that can't be copied but copying the others would be a big help. 
Or even add an additional step: show me the error message (as it is now), but then let me decide if I want to abort or if I want to continue anyway.

**Comment by d22** [comment]
Hi @mschwendener 
I will check what is possible, but I will definitely work on #8 first. If there are updates on this, I will let you know.
BR, Jonas

**Comment by d22** [comment]
Hi @mschwendener and @Raphael-Rey 
Version 1.2.0 of this CloudApp was just released. It is now possible to copy roles from users with invalid roles. The invalid roles will be skipped and reported after the copy process.
It is also possible to just compare roles of two users.
Please tell me if something does not work correctly or needs improvement.
br
Jonas
